### PR TITLE
Add support for youtube-key.txt for APP_KEY

### PR DESCRIPTION
**Pull request by glensc**
Benefit for the developer:
- Less copy/paste, shorter lines -> more readable code.

Benefit for the user:
- Can change the token of all libraries with one file change

### CODE REVIEW

**Comment by glensc** [comment]
I'm thinking that for consistency, should also support X-Plex-Token.id in plugin dir, and with .txt extension. WDYT?

**Comment by ZeroQI** [comment]
The token if only role is to download the library list so I could do logs per series

**Comment by glensc** [comment]
Providing files for other plugins is a weird design anyway. and not documented: find any word "hama" in readme.md

**Comment by ZeroQI** [comment]
Just read the code again. The Plex token if allows to read the plex library xml list to get name and root folder etc...
Forgot I used it in youtube agent as well for logs creation like I did for HAMA.

**Review by MattDemers — COMMENTED** [review]
This feels confusing; am I creating a new .txt file and putting it in the plugin directory, as in "inside the Plugins directory? Like, `Plugins/YouTube-Agent.bundle`? The same place at the `README.md` file? Feels like it needs a specific location.

**Comment by ZeroQI** [comment]
Place the value to `youtube-key.txt` file in the plugin directory
Not 'Plugins' but 'plugin' , the actual YouTube plugin folder.

**Comment by MattDemers** [comment]
Yes, I can; while just setting up, I didn't know if I was doing it correctly or not (since I'm having some issues in terms of some videos not showing up, some getting scraped and others not, etc). I basically wanted to make sure I was doing the right thing with the API, so I came to this instruction. 

Mostly just suggesting adding clarity to this; my Plex setup (Synology) has a folder structure of `Plug-ins/YouTube-Agent.bundle/Contents`, so I'm not exactly sure where `plugin` is.

**Comment by ZeroQI** [comment]
Plug-ins/YouTube-Agent.bundle

**Comment by MattDemers** [comment]
Thank you. I apologize for sounding sharp; just more suggesting the documentation could be clearer.

**Comment by ZeroQI** [comment]
Submit a change request and I will approve it...

**Pull request merged**
